---
name: PlantUML
on:
  push:
    paths:
    - '**.puml'
    tags-ignore:
    - '**'
    branches-ignore:
    - main
jobs:
  plantuml:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 2
    - uses: ts-graphviz/setup-graphviz@v1.1.0
    - uses: actions/cache@v3.0.11
      with:
        path: plantuml.jar
        key: ${{ runner.os }}-${{ hashFiles('plantuml.jar') }}
    - run: wget -N --no-verbose https://downloads.sourceforge.net/project/plantuml/plantuml.jar
    - name: Get changed UML files
      id: changed
      run: |
        git diff-tree -r --no-commit-id --name-status HEAD \
          | awk '
            $2 ~ /\.puml$/ &&
            $2 !~ /(theme|config)\.puml$/ &&
            $1 !~ /^D$/ {
              changed[++n]=$2
            }
            END {
              for ( i in changed ) result = result " " changed[i]
              printf "::set-output name=files::%s\n", result
              printf "::warning::%s\n", result
            }
          '
    - name: Get Removed UML files
      id: removed
      run: |
        git diff-tree -r --no-commit-id --name-status HEAD \
          | awk '
            $2 ~ /\.puml$/ &&
            $2 !~ /(theme|config)\.puml$/ &&
            $1 ~ /^D$/ {
              split($2, fn, ".")
              changed[++n]=fn[1] ".svg"
            }
            END {
              for ( i in changed ) result = result " " changed[i]
              printf "::set-output name=files::%s\n", result
              printf "::warning::%s\n", result
            }
          '
    - name: PlantUML Opts
      id: puml
      run: |
        OPTS="-tsvg -I.config/plantuml/theme.puml -verbose"
        echo "::set-output name=opts::$OPTS"
    - run: java -jar plantuml.jar -version
    - run: java -jar plantuml.jar ${{ steps.puml.outputs.opts }} ${{ steps.changed.outputs.files }}
      if: steps.changed.outputs.files != ''
    - run: java -jar plantuml.jar ${{ steps.puml.outputs.opts }} '**/*.puml'
      if: steps.changed.outputs.files == ''
    - uses: EndBug/add-and-commit@v9.1.1
      with:
        message: Generate SVG images for PlantUML diagrams
        add: ${{ steps.changed.outputs.files }}
        remove: ${{ steps.removed.outputs.files }}
        pull_strategy: NO-PULL
